version: '3'

services:
        extraordinary:
                build: "./Cryptography/Easy - Extraordinary"
                restart: always
                networks:
                        -  default
                ports: 
                        - "30030:30030"

        pick_your_poison:
                build: "./Cryptography/Medium - Pick Your Poison"
                restart: always
                networks:
                        -  default
                ports: 
                        - "30031:30031"
