version: '3.3'

# Ensure ASLR Is off!! echo 0 > /proc/sys/kernel/randomize_va_space
services:
    shell:
        build: "./Pwn/Easy - Pyshell"
        networks:
            - default
        ports:
            - "30010:30010"
    overwrite:
        build: "./Pwn/Easy - Overwrite"
        networks:
            - default
        ports:
            - "30011:30011"
    indirection:
        build: "./Pwn/Medium - Leap Frog"
        networks:
            - default
        ports:
            - "30012:30012"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        read_only: true
    house:
        build: "./Pwn/Hard - Indirection"
        networks:
            - default
        ports:
            - "30013:30013"
    bash:
            build: ./bash
            restart: always
            networks:
                    -  default
            ports:
                    - "30040:22"
    crack:
        build: "./Reversing/Easy - Crackme"
        networks:
            - default
        ports:
            - "30000:30000"
    interpret:
        build: "./Reversing/Medium - Interpreter"
        networks:
            - default
        ports:
            - "30001:30001"
    keygen:
        build: "./Reversing/Hard - Keygen"
        networks:
            - default
        ports:
            - "30004:30004"
    nodbg:
        build: "./Reversing/Hard - No Debugger"
        networks:
            - default
        ports:
            - "30005:30005"
    nested:
        build: "./Reversing/Insane - Nested"
        networks:
            - default
        ports:
            - "30002:80"
    encrypted:
        build: "./Reversing/Medium - Encrypted"
        networks:
            - default
        ports:
            - "30049:30049"
    extraordinary:
        build: "./Cryptography/Easy - Extraordinary"
        restart: always
        networks:
                -  default
        ports:
                - "30030:30030"
    pick_your_poison:
        build: "./Cryptography/Medium - Pick Your Poison"
        restart: always
        networks:
                -  default
        ports:
                - "30031:30031"
