version: '3.3'

# Ensure ASLR Is off!! echo 0 > /proc/sys/kernel/randomize_va_space
# Run docker-compose with --compatibility switch
# sudo docker-compose --compatibility up --build -d
# sudo docker-compose --compatibility down
services:
    shell:
        build: "./Pwn/Easy - Pyshell"
        networks:
            - default
        ports:
            - "30010:30010"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    overwrite:
        build: "./Pwn/Easy - Overwrite"
        networks:
            - default
        ports:
            - "30011:30011"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    indirection:
        build: "./Pwn/Medium - Leap Frog"
        networks:
            - default
        ports:
            - "30012:30012"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    house:
        build: "./Pwn/Hard - Indirection"
        networks:
            - default
        ports:
            - "30013:30013"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    bash:
            build: ./Bash
            networks:
                    -  default
            ports:
                    - "30040:22"
            deploy:
                resources:
                    limits:
                        cpus: '1.0'
                        memory: '32M'
            restart: always
            # read_only: true
    crack:
        build: "./Reversing/Easy - Crackme"
        networks:
            - default
        ports:
            - "30000:30000"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    interpret:
        build: "./Reversing/Medium - Interpreter"
        networks:
            - default
        ports:
            - "30001:30001"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    keygen:
        build: "./Reversing/Hard - Keygen"
        networks:
            - default
        ports:
            - "30004:30004"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    nodbg:
        build: "./Reversing/Hard - No Debugger"
        networks:
            - default
        ports:
            - "30005:30005"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    nested:
        build: "./Reversing/Insane - Nested"
        networks:
            - default
        ports:
            - "30002:80"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        # read_only: true
    encrypted:
        build: "./Reversing/Medium - Encrypted"
        networks:
            - default
        ports:
            - "30049:30049"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    extraordinary:
        build: "./Cryptography/Easy - Extraordinary"
        networks:
                -  default
        ports:
                - "30030:30030"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    pick_your_poison:
        build: "./Cryptography/Medium - Pick Your Poison"
        networks:
                -  default
        ports:
                - "30031:30031"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '32M'
        restart: always
        read_only: true
    web1:
            build: ./Web/web1
            networks:
                    - default
            ports:
                    - "30020:80"
            deploy:
                resources:
                    limits:
                        cpus: '1.0'
                        memory: '32M'
            restart: always
            # read_only: true
    web2:
            build: ./Web/web2
            networks:
                    - default
            ports:
                    - "30021:80"
            deploy:
                resources:
                    limits:
                        cpus: '1.0'
                        memory: '32M'
            restart: always
            # read_only: true
    web3:
            build: ./Web/web3
            networks:
                    - default
            ports:
                    - "30022:80"
            deploy:
                resources:
                    limits:
                        cpus: '1.0'
                        memory: '32M'
            restart: always
            # read_only: true
    web4:
            build: ./Web/web4
            networks:
                    - default
            ports:
                    - "30023:80"
            deploy:
                resources:
                    limits:
                        cpus: '1.0'
                        memory: '32M'
            restart: always
            # read_only: true
#     web5:
#             build: ./Web/web5
#             networks:
#                     - default
#             ports:
#                     - "30024:80"
#             deploy:
#                 resources:
#                     limits:
#                         cpus: '1.0'
#                         memory: '32M'
#             restart: always
            # read_only: true
