version: '3.3'

services:
    crack:
        build: "./Reversing/Easy - Crackme"
        networks:
            - default
        ports:
            - "30000:30000"
    interpret:
        build: "./Reversing/Medium - Interpreter"
        networks:
            - default
        ports:
            - "30001:30001"
    encrypted:
        build: "./Reversing/Medium - Encrypted"
        networks:
            - default
        ports:
            - "30049:30049"
    nested:
        build: "./Reversing/Insane - Nested"
        networks:
            - default
        ports:
            - "30002:30002"
